name: Tags
on: 
  push:
    tags:
      - nightly_build_**
jobs: 
  build:
    if: github.event.base_ref == 'ref/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          perfecto_token: "token"
          artifact_name: "Artifact.*"
          artifact_type: "zip/apk/apks/ipa"
          artifact_target: "development"
